BookManager-iOS
yshimizu-cq/BookManager_iOS pull request #1
Opened 2020-06-26 10:18 UTC by yshimizu-cq

## 概要　　
iOS書籍管理アプリのUI部分を実装しました。
レビューよろしくお願いします。

--------------------------------------
## 実装内容
- [x] ログイン画面
- [x] サインアップ画面
- [x] 書籍一覧画面
- [x] アカウント画面
- [x] 書籍追加画面
- [x] 書籍編集画面

--------------------------------------
## 確認項目
* 画面遷移や各機能の動作は確認済みだが、もっと良い書き方がないか
* コードが冗長になっていないか
* gitignoreの対象はこれでよいか
をご確認頂きたいです。  

--------------------------------------
## 関連URL
* [仕様書](https://www.dropbox.com/home/all/%E7%A4%BE%E5%86%85/%E7%A0%94%E4%BF%AE%E8%B3%87%E6%96%99?preview=20200416_bookManager_outline.xlsx)

--------------------------------------
## UI部分のスクリーンショット
- ログイン画面
![screen_login](https://user-images.githubusercontent.com/66235550/85845762-b9bd4380-b7df-11ea-94cc-f1fd0a5d1f19.png)
- サインアップ画面
![screen_signup](https://user-images.githubusercontent.com/66235550/85845830-d9ed0280-b7df-11ea-92c3-2d9c9d9919bb.png)
- 書籍一覧画面
![screen_book_list](https://user-images.githubusercontent.com/66235550/85845856-e7a28800-b7df-11ea-802f-10a5e31d10bc.png)
- アカウント画面
![screen_account](https://user-images.githubusercontent.com/66235550/85845889-f426e080-b7df-11ea-9f03-0ae5869b1aa7.png)
- 書籍追加画面
![screen_add_book](https://user-images.githubusercontent.com/66235550/85845907-fa1cc180-b7df-11ea-8517-f57e1858f10e.png)
- 書籍編集画面
![screen_edit_book](https://user-images.githubusercontent.com/66235550/85845929-0012a280-b7e0-11ea-8778-e65d3a6e522b.png)
- ログイン時バリデーション
[![Image from Gyazo](https://i.gyazo.com/bfeef3aa8071ad83a3d4fb464ae43615.gif)](https://gyazo.com/bfeef3aa8071ad83a3d4fb464ae43615)
- 書籍追加時DatePicker
[![Image from Gyazo](https://i.gyazo.com/620c6070eae9d44d018fda9463daadd4.gif)](https://gyazo.com/620c6070eae9d44d018fda9463daadd4)
- ログアウト時ダイアログ
[![Image from Gyazo](https://i.gyazo.com/ed456736510709afef7c830d7e8c5351.gif)](https://gyazo.com/ed456736510709afef7c830d7e8c5351)

2020-06-29 06:45 UTC, ikawashima-cq reviewed
コメントしました！
基本的に同じ指摘は１度しかしていないので、指摘していない部分でも当てはまっているところがあります
なので全体的に見直してみてください 🙆‍♀️

2020-06-29 06:45 UTC, ikawashima-cq commented on .gitignore
> +photos/
余分なファイルを差分に出さないようにする意図だと思うのでよきです 😃 

→iOSの場合は、画像はassetに追加するが基本になります。
今回はあとで削除する不要なファイルを置いている認識なのでこのままでもよいです

2020-06-29 06:45 UTC, ikawashima-cq commented on .swiftlint.yml
> +- BookManager_iOS/SceneDelegate.swift
SceneDelegateは今後（iOS13以降の起動処理）で使う可能性があるので基本的にはignoreしなくてよいです。
iOS13用の起動処理を対応するか、不要であれば削除ですね

→研修であれば iOS11〜iOS13の対応（2世代前までの対応）になると思うのでiOS13の場合はif #available(iOS 13, *)をつけて対応する形になるかと思います

2020-06-29 06:45 UTC, ikawashima-cq commented on .swiftlint.yml
> +- Carthage/
どちらもパッケージ管理ツールなので基本的に1つで統一したいです
Webでいうところのnpmとyarnをどっちも使っているというような状態なので単純に気持ち悪いです 😅

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +class AccountViewController: UIViewController {
Swiftでは継承しない場合は、final をつけてください

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        self.present(logoutDialog, animated: true, completion: nil)
``` completion: nil ``` についてはデフォルト引数なので省略しましょう！

Cmd + clickでメソッドの引数などを確認できるのでpresentメソッドのリファレンスを確認してみてください 👍

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        self.navigationItem.title = "アカウント"
基本的にはハードコードしたくないので
stringファイルを用意してそちらに文言は記載して、タイプセーフにしたいです 
stringファイルに記載すれば、R.string.localizable.acount() のような形で取得できます

https://i-app-tec.com/ios/localization.html

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        logoutDialog.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: nil))
このhandlerもデフォルト引数だったと思うので省略可能です！

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +          let storyboard: UIStoryboard = R.storyboard.login()
R.storyboard.login().instantiateInitialViewController()としてViewControllerまで取得してよいと思います。

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        self.view.backgroundColor = UIColor.white
基本的にクロージャー 内でなければselfは不要です。また、方が明示的なので .whiteだけで大丈夫です

```
view.backgroundColor = .white
```

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    let titleLabel: UILabel = {
AddBookViewControllerクラス外から参照したくないので privateをつけましょう !!!

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "完了", style: .plain, target: self, action: #selector(saveButtonTapped(_:)))
UIBarButtonItemも他のUIのパーツと同じようにプロパティとして持ってもよいかと思います

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        datePicker.date = Date()
> 他のUIのパーツと同じようにプロパティとして持ってもよいかと思います

同上です 🙄

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        toolbar.setItems([spacelItem, doneItem], animated: true)
> 他のUIのパーツと同じようにプロパティとして持ってもよいかと思います

同上です 🙄

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        guard !title.isEmpty, !price.isEmpty, !date.isEmpty else {
nilチェックと空文字チェックは、同じguard 文にまとめられるので1つにしたいです

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    @objc func saveButtonTapped(_ sender: UIBarButtonItem) {
メソッド名が動詞始まりでよいのですが、swiftの場合は、did~~ , will ~~ といった命名が多いです
今回の場合で言えば、``` didSaveButtonTapped ``` のような感じです。

この辺は言語によって違うので使い分けていく感じになるかと思います

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AppDelegate.swift
> -    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
不要なものは基本消していきたいのでよきです 😃

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListCell.swift
> +        addSubview(titleLabel)  //  Viewの配置
イニシャライザの中で処理が多いので
関数を作って抜き出すのが良さそうです！

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListCell.swift
> +    let titleLabel: UILabel = {
reuseIdentifierはこのクラスに紐づくものなのでこのクラスで指定あげた方がいいですね

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
可読性をあげるためにUITableViewDelegate, UITableViewDataSourceはextensionでわけて以下のように書きます。

```
final class BookListViewController: UIViewController {
      override func viewDidLoad() {
        super.viewDidLoad()
      }
}

extension UITableViewDataSource {
       //  セルをインスタンス化
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        cell.accessoryType = UITableViewCell.AccessoryType.disclosureIndicator

        return cell
    }

    //    セルの高さを指定
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 150
    }
}
```

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/EditBook/EditBookViewController.swift
> +            self.view.endEditing(true)
インデント 👮 

全選択してCtrl + i すれば一括修正できます

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +            self.view.endEditing(true)
インデント 👮‍♀️

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +    @IBOutlet weak var passwordTextField: UITextField!
IB でプロパティを宣言している場合は以下のようにして書いてまとめます

```
@IBOutlet weak var passwordTextField: UITextField! {
       didSet {
            passwordTextField.isSecureTextEntry = true
       }
}
```

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/MainTabController.swift
> +
この辺つめといてください

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Logout/LogoutViewController.swift
> +    override func viewDidLoad() {
基本的に統一したコードを書きたいので
1行あけるならあけると統一性を持たせたいです !!

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/MainTabController.swift
> +//        viewControllers.append(bookListViewController)  // append => 配列に追加
コメントアウトも不要なので削除しておいてください！
どうしても残したい場合は git stashしておくでよいと思います

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Navigation/UITabBarViewController.swift
> +class UITabBarViewController: UIViewController {
なんか同じようなクラス2つできてますね 🙄 

こちら不要だと思うので削除しておいてください

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Protocol/ValidatorProtocol.swift
> +protocol CompositeValidator: Validator {
プロトコル使っているのであれば基本的にどこかしらのクラスか構造体に準拠させないと使えない認識です

のでもし使う場合は、使うような変更をお願いします 🙆‍♂️

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/SceneDelegate.swift
> +        // bad
上述したように特に使わないようならappDelegateのみでこちらは削除でよいと思います

2020-06-29 06:45 UTC, ikawashima-cq commented on SomeViewController.swift
> +import Foundation
このファイル・クラスも使っていないなら削除で 🙏

2020-06-29 06:45 UTC, ikawashima-cq commented on Podfile
> +  pod 'SwiftLint'
基本的に2つ使っているメリットないと思うのでPodは削除、SwiftLintは.swiftlint.ymlファイルでルールを定義してRunScriptで実行するよう修正でお願いします 👍 

ちなみにPodの方が導入は簡単ですが、ビルド時に毎回ライブラリのソースファイルをコンパイルしにいくのでビルドが遅いです。
なので業務では基本carthage。どうしてもcarthageでいれられない（基本的にはない認識ですが）場合は悔し涙を流しながらPodで導入するといった感じです 😢

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Singup/SignupViewController.swift
> +    private func alertMessage(message: String) {
``` showAlert ``` のような命名の方がよく使いますかね

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Singup/SignupViewController.swift
> +    @IBAction func passwordTextField(_ sender: UITextField) {
メソッドなので動詞始まりにて 👮

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +        let alert = UIAlertController(title: "入力エラー", message: message, preferredStyle: .alert)
アラートはどの画面（クラス）でも使っているので共通なモジュールを作って
それを各クラスでの処理に応じてカスタマイズして使うのがよいと思います

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        imageView.image = UIImage(named: "sample_image")
assetに追加している場合は、R.image.~~ とすれば取得できます！

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "完了", style: .plain, target: self, action: #selector(saveButtonTapped(_:)))
あと長いのでこのような場合は適宜改行します

```
UIBarButtonItem(title: "完了",
                            style: .plain, 
                            target: self, 
                            action: #selector(saveButtonTapped(_:))
)
```

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        titleTextField.delegate = self
let を lazy varにすれば上のプロパティクロージャー 内部で
titleTextField.delegate = self とselfを使えるようになります

2020-06-29 06:45 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        datePicker.datePickerMode = UIDatePicker.Mode.date
.dateでよさそうです

2020-06-29 06:48 UTC, ikawashima-cq commented
あとPRの概要欄で スクショを貼るときにtable形式で貼ると良いです 
https://techlife.cookpad.com/entry/2016/08/17/111500

ベタばりだとちょっとインパクトがありすぎるので 🙃

2020-06-29 08:37 UTC, ikawashima-cq commented
あとそういえば、

## APIで受け取ったデータ（今だとダミーデータ）を表示用に変換する
  - 書籍一覧画面での 〜〜円　と表記つける
  - 購入日も然りです。（スラッシュかハイフンか）

## 書籍追加画面と編集画面でテキストフィールドが見えなくなってしまう可能性がある。
  - 購入日のテキストフィールドがギリギリいまは見えていますが、端末を変更したときに見えなくなる可能性もあることを考慮して、キーボードが表示されたらその分画面を擦り上げる処理を追加してもいいかなと思いました。

2020-06-30 08:43 UTC, yshimizu-cq commented on .gitignore
> +photos/
assetへの追加が基本とのこと、了解です。今回はこのままにさせて頂きます。

2020-06-30 08:43 UTC, yshimizu-cq commented on .swiftlint.yml
> +- Carthage/
確かにそう言われてみるとおかしいですね…
CocoaPodsをアンインストールしてCarthageに統一しました！

2020-06-30 08:43 UTC, yshimizu-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +class AccountViewController: UIViewController {
他ファイル含め、継承してない場合は`final`をつけました

2020-06-30 08:43 UTC, yshimizu-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        self.present(logoutDialog, animated: true, completion: nil)
リファレンス確認し、デフォルト引数が`nil`だったので省略しました。
また他ファイルも同様に変更しました。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        self.navigationItem.title = "アカウント"
Stringファイルを作成し、R.string.localizableを使った書き方に変更しました。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        logoutDialog.addAction(UIAlertAction(title: "Cancel", style: .cancel, handler: nil))
リファレンス確認し、デフォルト引数が`nil`だったので省略しました。
また他ファイルも同様に変更しました。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +          let storyboard: UIStoryboard = R.storyboard.login()
ViewControllerまで取得する形に書き換えました。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        self.view.backgroundColor = UIColor.white
selfと型を省略しました。
他ファイルも同様に確認済です。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    let titleLabel: UILabel = {
クラス外参照の場合はすべてprivateを付けました。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        self.navigationItem.rightBarButtonItem = UIBarButtonItem(title: "完了", style: .plain, target: self, action: #selector(saveButtonTapped(_:)))
他UIパーツと同様にプロパティとして持つように変更しました。
他ファイルも変更しています。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        datePicker.date = Date()
他UIパーツと同様にプロパティとして持つように変更しました。
他ファイルも変更しています。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        toolbar.setItems([spacelItem, doneItem], animated: true)
他UIパーツと同様にプロパティとして持つように変更しました。
他ファイルも変更しています。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    @objc func saveButtonTapped(_ sender: UIBarButtonItem) {
他のメソッドも含めて、メソッド名を修正しました。

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/AppDelegate.swift
> -    func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration {
ありがとうございます！

2020-06-30 08:44 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListCell.swift
> +        addSubview(titleLabel)  //  Viewの配置
Ankerを関数を使って抜き出しました。

2020-06-30 08:45 UTC, yshimizu-cq commented on BookManager_iOS/EditBook/EditBookViewController.swift
> +            self.view.endEditing(true)
すみません。気付きませんでした。
ショートカット教えていただきありがとうございます！

2020-06-30 08:45 UTC, yshimizu-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +            self.view.endEditing(true)
すみません。気付きませんでした。
ショートカット教えていただきありがとうございます！

2020-06-30 08:45 UTC, yshimizu-cq commented on BookManager_iOS/MainTabController.swift
> +//        viewControllers.append(bookListViewController)  // append => 配列に追加
すみません、確認漏れです。
不要なので削除しました。

2020-06-30 08:45 UTC, yshimizu-cq commented on BookManager_iOS/Navigation/UITabBarViewController.swift
> +class UITabBarViewController: UIViewController {
すみません。Xcode上で削除できているのですが、ローカルに残っておりpushしてしまっていました。
git addする前に、ファイル確認するようにします。

2020-06-30 08:45 UTC, yshimizu-cq commented on BookManager_iOS/Protocol/ValidatorProtocol.swift
> +protocol CompositeValidator: Validator {
すみません。こちらも同上です。

Xcode上で削除できているのですが、ローカルに残っておりpushしてしまっていました。
git addする前に、ファイル確認するようにします。

2020-06-30 08:45 UTC, yshimizu-cq commented on SomeViewController.swift
> +import Foundation
すみません。こちらも不要ファイルです。

Xcode上で削除できているのですが、ローカルに残っておりpushしてしまっていました。
git addする前に、ファイル確認するようにします。

2020-06-30 08:45 UTC, yshimizu-cq commented on Podfile
> +  pod 'SwiftLint'
PodをアンインストールしてCarthageに統一しました。

なるほど、勉強になります！
それぞれのメリデメ自分でも確認しておきます。

2020-06-30 08:45 UTC, yshimizu-cq commented on BookManager_iOS/Singup/SignupViewController.swift
> +    private func alertMessage(message: String) {
他ファイル含めshowAlertに変更しました。

2020-06-30 09:11 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
UITableViewDelegateとUITableViewDataSourceをextensionで切り出しました。

2020-06-30 09:22 UTC, yshimizu-cq commented on BookManager_iOS/MainTabController.swift
> +
全体の行の空け方を統一しました。

2020-06-30 09:22 UTC, yshimizu-cq commented on BookManager_iOS/Logout/LogoutViewController.swift
> +    override func viewDidLoad() {
全体的に行の空け方を統一しました。

2020-06-30 09:46 UTC, yshimizu-cq commented on BookManager_iOS/Singup/SignupViewController.swift
> +    @IBAction func passwordTextField(_ sender: UITextField) {
他メソッドも含めて動詞始まりに変更しました。

2020-06-30 09:46 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        imageView.image = UIImage(named: "sample_image")
なるほど！Rswift便利です。
修正しました。

2020-06-30 10:04 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        titleTextField.delegate = self
lazy varを使ってクロージャー内に記載しました。

2020-06-30 10:04 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        datePicker.datePickerMode = UIDatePicker.Mode.date
.dateの省略形に変更しました。

2020-07-01 02:57 UTC, yshimizu-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +        let alert = UIAlertController(title: "入力エラー", message: message, preferredStyle: .alert)
extensionで切り出して共通化しました。

2020-07-01 02:57 UTC, yshimizu-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +    @IBOutlet weak var passwordTextField: UITextField!
他のViewControllerも含めて、didSetの書き方に変更しました。

2020-07-01 03:06 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        guard !title.isEmpty, !price.isEmpty, !date.isEmpty else {
nilチェックと空文字チェックを同じguard文にまとめました。

2020-07-01 03:08 UTC, ikawashima-cq reviewed
@yshimizu-cq 

まだ修正中かもしれないですが、
いくつかコメントしました 👍

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +class AddBookViewController: UIViewController, UITextFieldDelegate {
final ですね 👮

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +    @objc func didAddBarButtonTapped(_ sender: UIBarButtonItem) {
``` @objc private func  ``` ですね

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    private lazy var toolBar: UIToolbar = { [weak self] in
クロージャー 内でself使っていないので letで良いです。
また[weak self]不要

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    private let spacelItem: UIBarButtonItem = {
クロージャー 内でself使っているので lazy var

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        let doneitem = UIBarButtonItem.init(barButtonSystemItem: .done,
この辺書き方にもよるのですが initいらないです

```
UIBarButtonItem(barButtonSystemItem: .done,
```

型を明示的に書いていれば  以下のようにもかけますが、統一性をもたせたいので上の書き方でよいかと思います
```
let doneitem: UIBarButtonItem = .init(barButtonSystemItem: .done,
```

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/BookListCell.swift
> +class BookListCell: UIViewController {
このクラスもいらなそうですね 🙄 
削除でお願いします 🙏

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListCell.swift
> +        imageView.image = UIImage(named: R.string.localizable.sampleImage())
👍

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        }()
インデント 👮

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +    private lazy var rightBarButton: UIBarButtonItem = { [weak self] in     //  lazy var => 呼び出された時に初期値決定
[weak self] in   は不要です

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        tableView.register(BookListCell.self, forCellReuseIdentifier: "cell")
この辺りも 上のtableviewのプロパティとしてまとめたいです

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        guard let editBookViewController = storyboard.instantiateInitialViewController() as? EditBookViewController else { return }
不要な一時変数はなるべくおきたくないので
R.storyboard.editBook().EditBookViewController()! のような形で1行でまとめましょうか

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +        let minimumLengthOfCharactors = 6
アプリ固有のロジックに関わる数字になる認識なので
これは定数としてもちたいですね

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/Logout/LogoutViewController.swift
> +class LogoutViewController: UIViewController {
final

2020-07-01 03:08 UTC, ikawashima-cq commented on BookManager_iOS/MainTabController.swift
> +        guard let account = storyboard.instantiateInitialViewController() as? AccountViewController else { return }
上でも書きましたが、
ViewControllerの場合は、アンラップしてよいと思います。

というのもすでにViewControllerがあることが明確（StoryBoardで作ってますよね）である。

仮にViewControllerがなくguardで抜けた場合に、画面が表示されず真っ暗な画面になってしまいます。
結果としてユーザーは操作できずに混乱を与えてしまいます。それであればクラッシュさせた方が賢明という判断です。

2020-07-01 03:08 UTC, ikawashima-cq commented on Cartfile
> +github "ishkawa/APIKit" ~> 5.0
apikit は今回は不要になるため、こちらの記載を削除した上で
carthage updateをかけておいてください 🙏 


また、プロジェクトファイルの設定の削除も然りです

2020-07-01 03:49 UTC, yshimizu-cq commented on BookManager_iOS/SceneDelegate.swift
> +        // bad
不要なのでSceneDelegateを削除しました。

2020-07-01 03:50 UTC, yshimizu-cq commented on .swiftlint.yml
> +- BookManager_iOS/SceneDelegate.swift
SceneDelegateの役割とif #availableによるバージョン判定の方法、分かっていなかったので確認しました。
今回は不要なので、削除して対応しました。

2020-07-01 05:21 UTC, ikawashima-cq commented on BookManager_iOS/Extension/UIAlertExtension.swift
> +public extension UIViewController {
publicなしで大丈夫です！

> public | 別モジュールから呼び出せるが継承やオーバーライドが不可能

ライブラリのメソッドなどでよくpublicがつきますね（気になったらNukeとかで確認してみてください 🙏 ）
https://qiita.com/GATA/items/90341f56a56ff584e756

2020-07-01 07:03 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    private lazy var toolBar: UIToolbar = { [weak self] in
循環参照で無かったため、[ weak self ]を削除しました。 

クロージャー内で `width: view.frame.size.width`を使っているため、lazy varにしないとエラー出てしまいますが、他の書き方にした方が良いでしょうか＊

2020-07-01 07:03 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +    @objc func didAddBarButtonTapped(_ sender: UIBarButtonItem) {
他メソッドも確認し、privateにしました。

2020-07-01 07:03 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +class AddBookViewController: UIViewController, UITextFieldDelegate {
すみません、見落としてました。

2020-07-01 07:05 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    private lazy var toolBar: UIToolbar = { [weak self] in
そうでしたね 😅  lazy varで大丈夫です

2020-07-01 07:15 UTC, ikawashima41 commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +class AddBookViewController: UIViewController, UITextFieldDelegate {
大丈夫です！
慣れない中でミス多くなると思っているのでどうやったら少なくできそうか模索してみてください 👍

2020-07-01 07:22 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    private let spacelItem: UIBarButtonItem = {
他ViewController含め、lazy varに変更しました。

2020-07-01 07:23 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        let doneitem = UIBarButtonItem.init(barButtonSystemItem: .done,
なるほど、省略できるんですね。勉強になります。

2020-07-01 07:23 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/BookListCell.swift
> +class BookListCell: UIViewController {
すみません、消し忘れです。
削除しました。

2020-07-01 07:23 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +    private lazy var rightBarButton: UIBarButtonItem = { [weak self] in     //  lazy var => 呼び出された時に初期値決定
他メソッド、ViewController含め削除しました。

2020-07-01 07:23 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        tableView.register(BookListCell.self, forCellReuseIdentifier: "cell")
他UIパーツ同様、プロパティとしてまとめました。

2020-07-01 07:35 UTC, yshimizu-cq commented on BookManager_iOS/Logout/LogoutViewController.swift
> +class LogoutViewController: UIViewController {
すみません、不要ファイルのため削除しました。

2020-07-01 07:35 UTC, yshimizu-cq commented on Cartfile
> +github "ishkawa/APIKit" ~> 5.0
APIKit使わないこと承知しました。
削除してupdateしました。

2020-07-01 07:36 UTC, yshimizu-cq commented on BookManager_iOS/Extension/UIAlertExtension.swift
> +public extension UIViewController {
public, internal, privateの範囲の理解が不十分でした。。
public削除しました。

2020-07-01 07:38 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +    private lazy var toolBar: UIToolbar = { [weak self] in
了解です！ありがとうございます。
lazy varのままにしておきます。

2020-07-01 07:43 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        }()
すみません、修正しました！

2020-07-01 08:58 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        guard let editBookViewController = storyboard.instantiateInitialViewController() as? EditBookViewController else { return }
R.storyboard.editBook.instantiateInitialViewController()!
の書き方でアンラップして取得しました！

2020-07-01 08:58 UTC, yshimizu-cq commented on BookManager_iOS/MainTabController.swift
> +        guard let account = storyboard.instantiateInitialViewController() as? AccountViewController else { return }
なるほど、ユーザー目線で考えれてなかったです。勉強になります！

R.storyboard.signup.instantiateInitialViewController()!
の書き方でアンラップして取得しました！

2020-07-01 09:00 UTC, yshimizu-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +        let minimumLengthOfCharactors = 6
グローバル定数として`Minimum_Length_Of_Charactors`で定義しました。
SignupViewControllerの方も同様に変更しました。

2020-07-01 10:22 UTC, ikawashima-cq approved these changes
@yshimizu-cq 

少しコメントしましたが、良さそうなので先にapproveします 
修正したら小村さんにレビュー依頼お願いします 👍 

![LGTM](https://cdn.lgtmoon.dev/images/90283)

2020-07-01 10:22 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +                                 object: nil
いいですね 😺

2020-07-01 10:22 UTC, ikawashima-cq commented on BookManager_iOS/EditBook/EditBookViewController.swift
> +            !title.isEmpty, !price.isEmpty, !date.isEmpty else {
ここも上と同じように改行したほうがよいですかね

2020-07-01 10:22 UTC, ikawashima-cq commented on BookManager_iOS/Singup/SignupViewController.swift
> +        let Minimum_Length_Of_Charactors = 6
なるほど。
定数は以下のようにまとめますね。あとSwiftの場合はキャメルケースで、スネークケースを使うことはほぼないです
今回であればSignupViewControllerで使う認識なので グローバルにせずにprivate でもつ感じでよいと思います

```
final class SignupViewController: UIViewController {
　private struct Const {
     　　static let minimumLengthOfCharactors: Int = 6
　 }
     
    @IBAction func signupButtonTapped(_ sender: UIButton) {
           Const.minimumLengthOfCharactors -> こんな感じで呼びます
    }
}
```

2020-07-01 10:22 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
"cell"　もハードコードを避けたいので定数で持つ感じのほうがいいですね

登録するcellが複数になったり、identifier変えたいときにやりやすいです

Cellに紐づくものなのでCellクラスの方で定数として持っておくとよいかと思います 🙏 
```
final class BookListCell: UITableViewCell { 
     static let identifier: String = "cellIdentifier"
}

BookListCell.identifier -> これで呼び出します
```

2020-07-01 10:49 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListCell.swift
> +    let titleLabel: UILabel = {
BookListCellでidentiferを指定しました。

2020-07-01 10:57 UTC, yshimizu-cq commented on BookManager_iOS/EditBook/EditBookViewController.swift
> +            !title.isEmpty, !price.isEmpty, !date.isEmpty else {
他のViewControllerも含めて改行しました。

2020-07-01 11:12 UTC, yshimizu-cq commented on BookManager_iOS/Singup/SignupViewController.swift
> +        let Minimum_Length_Of_Charactors = 6
丁寧に提示して頂きありがとうございます。勉強になります。
訂正しました。

2020-07-01 11:12 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
直接のご指導ありがとうございました！
修正しました。

2020-07-01 13:50 UTC, ghost requested changes
実装早いですね！
それにコードも綺麗です！

修正したらまた依頼お願いします！

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        logoutDialog.addAction(UIAlertAction(title: R.string.localizable.noProblem(), style: .default,
styleも改行した方がコードがみやすいですね💪

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        self.present(logoutDialog, animated: true)
self省略できると思います！

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        let editBookViewController = R.storyboard.editBook.instantiateInitialViewController()!
何らかの理由でインスタンスが生成できない可能性もあるので、guard文書いちゃいましょうか！

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +        let signupView = R.storyboard.signup.instantiateInitialViewController()!
ここもguardにしちゃいましょう！

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/MainTabController.swift
> +        let account = R.storyboard.account.instantiateInitialViewController()!
ここもです！

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        view.addSubview(imageUploadButton)
DRYに反しているので、いい感じに書き直しちゃいましょう！

```
[titleLabel, titleTextField, priceLabel, priceTextField, ...].forEach {  view.addSubview($0) }
```

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        self.dismiss(animated: true)
self省略できますね！

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        self.view.endEditing(true)
ここもです！

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +            self.view.transform = transform
ここ循環参照してる可能性あるので、

```
UIView.animate(withDuration: duration) { [unowned self] in
```

しちゃいましょうか！

2020-07-01 13:50 UTC, yomura-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        }
ここも循環参照してる可能性ありです！

2020-07-02 01:30 UTC, yshimizu-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        logoutDialog.addAction(UIAlertAction(title: R.string.localizable.noProblem(), style: .default,
styleの改行追加しました！

2020-07-02 01:30 UTC, yshimizu-cq commented on BookManager_iOS/Account/AccountViewController.swift
> +        self.present(logoutDialog, animated: true)
self省略しました！
他ファイルも確認しself省略できるところは省略しました。

2020-07-02 01:30 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        self.dismiss(animated: true)
self省略しました！
他ファイルも確認しself省略できるところは省略しました。

2020-07-02 01:30 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        self.view.endEditing(true)
self省略しました！
他ファイルも確認しself省略できるところは省略しました。

2020-07-02 01:43 UTC, ikawashima-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        }
基本的にはiOS標準のAPIでは常に[weak self], [unowned self] をつける必要ないと思っていて
以下の記事にあるように動作が異なりそうなときだけ考慮するようにしています。今回に関しては不要の認識です

https://qiita.com/HIkaruSato/items/1f17baf43b943949a7ff

2020-07-02 01:44 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        let editBookViewController = R.storyboard.editBook.instantiateInitialViewController()!
`guard let ... else { return }`で書き換えました！

2020-07-02 01:44 UTC, yshimizu-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +        let signupView = R.storyboard.signup.instantiateInitialViewController()!
`guard let ... else { return }`で書き換えました！

2020-07-02 01:44 UTC, yshimizu-cq commented on BookManager_iOS/MainTabController.swift
> +        let account = R.storyboard.account.instantiateInitialViewController()!
`guard let ... else { return }`で書き換えました！

2020-07-02 01:45 UTC, ikawashima-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        let editBookViewController = R.storyboard.editBook.instantiateInitialViewController()!
ここに関しては、☝️で言及してますが、値がくることが保証されているので暗黙的アンラップにしてもらってます

2020-07-02 02:16 UTC, yshimizu-cq commented on BookManager_iOS/BookList/BookListViewController.swift
> +        let editBookViewController = R.storyboard.editBook.instantiateInitialViewController()!
なるほど、nilにならないことを自分で保証できる場合は "!"で暗黙的アンラップする方が良いのですね。
guard文との使い分けをしっかり理解できていなかったので確認しました。
今回はアンラップする書き方で記述します。

2020-07-02 02:16 UTC, yshimizu-cq commented on BookManager_iOS/Login/LoginViewController.swift
> +        let signupView = R.storyboard.signup.instantiateInitialViewController()!
同上でアンラップする書き方にしました！

2020-07-02 02:16 UTC, yshimizu-cq commented on BookManager_iOS/MainTabController.swift
> +        let account = R.storyboard.account.instantiateInitialViewController()!
同上でアンラップする書き方にしました！

2020-07-02 02:29 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +            self.view.transform = transform
川島さん提供記事を参考に今回はこのままでいきます。
[weak self] [unowned self]の使い分けも理解不十分だったので確認しました。

2020-07-02 02:29 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        }
川島さん提供記事を参考に今回はこのままでいきます。
[weak self] [unowned self]の使い分けも理解不十分だったので確認しました。

2020-07-02 02:29 UTC, yshimizu-cq commented on BookManager_iOS/AddBook/AddBookViewController.swift
> +        view.addSubview(imageUploadButton)
なるほど、forEach便利です。書き直しました！

2020-07-02 02:31 UTC, yshimizu-cq commented
@yomura-cq 

迅速なレビュー対応ありがとうございました！
ご指摘頂いた点を修正しましたので、お手数ですが、再度レビューお願いします！
一部、川島さん助言も参考にしながら変更していない部分もあります。

2020-07-02 02:43 UTC, ghost approved these changes
完璧です！

次三好さんにレビュー依頼お願いします！

2020-07-02 03:16 UTC, miyoshitakaaki approved these changes
LGTM、問題なさそうなので承認しておきますー

2020-07-02 03:16 UTC, miyoshi-cq commented on BookManager_iOS/EditBook/EditBookViewController.swift
> +        guard let rect = (notification?.userInfo?[UIResponder.keyboardFrameBeginUserInfoKey] as? NSValue)?.cgRectValue,
guardの前後に改行いれるともう少し見やすいかも

2020-07-02 03:16 UTC, miyoshi-cq commented on BookManager_iOS/AppDelegate.swift
> +    var navigationController: UINavigationController?
このプロパティどこで使ってる？
使ってなかったら削除で 🙏

2020-07-02 06:33 UTC, yshimizu-cq commented on BookManager_iOS/AppDelegate.swift
> +    var navigationController: UINavigationController?
使ってないです…消し忘れです。
削除しました。

2020-07-02 06:33 UTC, yshimizu-cq commented on BookManager_iOS/EditBook/EditBookViewController.swift
> +        guard let rect = (notification?.userInfo?[UIResponder.keyboardFrameBeginUserInfoKey] as? NSValue)?.cgRectValue,
他のViewControllerも含めて改行加えました！

2020-07-02 06:35 UTC, merged