Feature/create bookmanager api
yshimizu-cq/BookManager_iOS pull request #3
Opened 2020-07-08 09:12 UTC by yshimizu-cq

## 概要　　
iOS書籍管理アプリのAPI部分を実装しました。
レビューよろしくお願いします。

--------------------------------------
## 実装内容
- [x] ログイン画面
- [x] サインアップ画面
- [x] 書籍一覧画面
- [x] アカウント画面
- [x] 書籍追加画面
- [x] 書籍編集画面

--------------------------------------
## 確認項目
* 画面遷移や各機能の動作は確認済みだが、もっと良い書き方がないか
* コードが冗長になっていないか
をご確認頂きたいです。  

--------------------------------------
## 関連URL
* [仕様書](https://www.dropbox.com/home/all/%E7%A4%BE%E5%86%85/%E7%A0%94%E4%BF%AE%E8%B3%87%E6%96%99?preview=20200416_bookManager_outline.xlsx)

--------------------------------------
## UI部分のスクリーンショット
書籍一覧画面 | 
---- | 
<img src="https://user-images.githubusercontent.com/66235550/86899180-9f228d00-c144-11ea-9378-68764cb060e9.png" width="320"/> | 

書籍編集操作 | 下スクロール時データ読み込み
---- | ----
<img src="https://i.gyazo.com/080bea3b9af3525b722bc9ea5357c3e3.gif" width="320"/> | <img src="https://i.gyazo.com/91b24b25d2a070480e1b4a414b9e36d9.gif" width="320"/>

2020-07-09 02:02 UTC, ghost requested changes
レベル上がってますね！

コメント修正してみてください！

循環参照周り理解難しいですが、必須概念なので頑張ってみてください💪

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +            return "DELETE"
詰まって見えるのでスペースあけましょか！
```
        case .bookList:
            return "GET"

        case .login, .signup, .addBook:
            return "POST"

        case .editBook:
            return "PATCH"

        case .account:
            return "DELETE"
```

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +            return "logout"
ここもです！

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/View/Account/AccountViewController.swift
> +            self.present(logoutDialog, animated: true)
コールバックの中でself参照しているので、
```
accountViewModel.account(successAction: { [unowned self] in
```

こうしましょう！

循環参照防げます！

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/View/AddBook/AddBookViewController.swift
> +            self.dismiss(animated: true)
ここも循環参照してますね！

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +            self.bookTableView.reloadData()
ここも循環参照してますね！

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +            self.navigationController?.popViewController(animated: true)
ここもです！

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +            self.showAlert(message: error.message)
ここも！

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/View/Login/LoginViewController.swift
> +            self.showAlert(message: error.message)
循環参照ですね！

2020-07-09 02:02 UTC, ghost commented on BookManager_iOS/View/Singup/SignupViewController.swift
>          }
ここもです！

2020-07-09 02:02 UTC, caraquri-yomura commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    }
これカプセル化できそうですね！

基本的にviewModelはvalidateすることはないので(viewが扱いやすいようにdataを成形する役目)、validate専用のクラス作りましょうか！

河野さんがiOS研修でvalidateクラスを作られているので、そちら参考にしてみてくださ！
すごく綺麗なんで！

2020-07-09 02:35 UTC, caraquri-tmiyoshi commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    }
> 基本的にviewModelはvalidateすることはない

自分はViewModelがvalidate処理を持つのはありかなと
ViewControllerがプレゼンテーションロジック、ViewModelがデータロジックと定めれば全然許容できるかなー

validate専用クラスを作るのは構わないのだけど、局所的にしか使わない処理をそちらのクラスにまとめて、
どこからでも使えるようにするのは、ただただスコープを広げることになるので、
作り次第では賛成できないかもしれない 🤔 
emailの正規表現やpasswordの桁数がアプリ全体共通ということで、
それだけ別でまとめるということであれば全然良き

2020-07-09 02:38 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    }
確かに。JPICでも同様にvalidate専用クラスを作って局所的にしか使わない処理をまとめてますが、負の遺産になってますしね

2020-07-09 02:45 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    }
ご意見ありがとうございます！
validate専用クラス作ることのメリデメを理解した上で、今回どちらがベターか判断して修正します
勉強のため、河野さんのも確認してみます

2020-07-09 05:42 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +            return "DELETE"
条件分岐の際とコード可読性に配慮して、適宜空行追加しました。他ファイルも合わせて修正しました。

2020-07-09 05:42 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +            return "logout"
条件分岐の際とコード可読性に配慮して、適宜空行追加しました。他ファイルも合わせて修正しました。

2020-07-09 08:50 UTC, yshimizu-cq commented on BookManager_iOS/View/Account/AccountViewController.swift
> +            self.present(logoutDialog, animated: true)
unowned self を追記し修正しました。

2020-07-09 08:50 UTC, yshimizu-cq commented on BookManager_iOS/View/AddBook/AddBookViewController.swift
> +            self.dismiss(animated: true)
unowned self を追記し修正しました。

2020-07-09 08:50 UTC, yshimizu-cq commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +            self.bookTableView.reloadData()
unowned self を追記し修正しました。

2020-07-09 08:50 UTC, yshimizu-cq commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +            self.navigationController?.popViewController(animated: true)
unowned self を追記し修正しました。

2020-07-09 08:50 UTC, yshimizu-cq commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +            self.showAlert(message: error.message)
unowned self を追記し修正しました。

2020-07-09 08:50 UTC, yshimizu-cq commented on BookManager_iOS/View/Login/LoginViewController.swift
> +            self.showAlert(message: error.message)
unowned self を追記し修正しました。

2020-07-09 08:50 UTC, yshimizu-cq commented on BookManager_iOS/View/Singup/SignupViewController.swift
>          }
unowned self を追記し修正しました。

2020-07-09 12:18 UTC, caraquri-ikawashima reviewed
@yshimizu-cq 

ちょっとレビューが詰まっているので先にコメントしました!!
複数当てはまっているものでも一度しか指摘していないので全体的に見直してみてください 👍

@caraquri-yomura
指摘あれば指摘してもらって大丈夫ですし、
小村さん的にOKであれば よきタイミングでapproveお願いします 👍

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +        var components = URLComponents(string: "http://54.250.239.8/\(type.path)")
``` "http://54.250.239.8/ ```  BaseURLとして定義したいですね

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Response/Response.swift
> +import Foundation
このファイル不要であれば削除でお願いします 🙏

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/View/Account/AccountViewController.swift
> +        }) { error in
何かしらエラーハンドリングはしたほうがよいかと思います（アラートで表示するなり）

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +    static func constructor(book: Book) -> EditBookViewController {
あまりswiftではconstructorとは呼ばないですね（イニシャライザといっています）

factoryメソッドなので makeInstance やcreateInstanceのような命名になるかと思います。

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +        Nuke.loadImage(with: url, into: imageView)
nukeで画像を表示させるメソッドを各所で使っているので
UIImageViewの拡張などで一箇所にまとめてあげてもよいかと思います

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/Account/AccountViewModel.swift
> +    func account(successAction: @escaping () -> Void, errorAction: @escaping (Error) -> Void) {
account  = logoutですかね？？ 
logoutやsignoutでよいかと思います

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    enum EditBookError: Error {
エラーに関しては、ステータスコード別や状況別（decodingエラーなど）に一箇所にまとめて、各画面で使うような感じでよいかと思います。

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +                UserDefaultsUtil.set(value: inputValue.id ?? 0, forKey: "book")
ここidを保存しているのって何か理由ありですか？？？ 🤔

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    var keychain: Keychain {
keyChainのこのプロパティってkeychainのmanager的なところにもあったと思うのでそちらを使うような形にした方がよいと思います。
また、値のget/setメソッドもkeychainのmanager的なところにもたせてあげれば各画面でimport KeychainAccessする必要もなくなると思います。

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/test.swift
> +//
このファイルも不要そうですね 🙄

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +    case login(UserRequest)
これ自分が簡易に作ったサンプルとして出回ってしまったのですが 😢 
実際のプロジェクトではそれぞれのリクエストをクラスなり構造体などで定義しています。 
（その中のmethodやpathなどリクエストを構成する要素はenumでまとめたりもするのですが）

なのでloginならloginRequest, signUpならsignUpRequestのようにそれぞれ定義してあげてください 🙏

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Request/UserDefaultsUtil.swift
> +        UserDefaults.standard.set(value, forKey: forKey)
firstLaunch以外に保存する値ってありますかね？
もしなければ 以下のようにして良さそうです

```
func setLaunchFlag(value: Any) {
    UserDefaults.standard.set(value, forKey: "isFirstLaunch" )
}
```

2020-07-09 12:18 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +        var request = URLRequest(url: url!)
アンラップしたくないのでオプショナルバインディングしましょうか

2020-07-13 01:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    }
今回は、validation処理は局所的にしか使わないのでViewModelで持つ方がベターだと言うことを理解した上で、練習のためvalidation専用のクラスを作って呼び出す形で書いてみました。

2020-07-13 01:42 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +        var components = URLComponents(string: "http://54.250.239.8/\(type.path)")
BaseURLとして定義しました！

2020-07-13 01:44 UTC, yshimizu-cq commented on BookManager_iOS/Model/Response/Response.swift
> +import Foundation
確認不足すみません…削除しました。

2020-07-13 02:24 UTC, yshimizu-cq commented on BookManager_iOS/View/Account/AccountViewController.swift
> +        }) { error in
アラート表示するよう変更しました！

2020-07-13 02:29 UTC, yshimizu-cq commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +    static func constructor(book: Book) -> EditBookViewController {
なるほど。勉強になります。
makeInstanceに変更しました。

2020-07-13 02:31 UTC, yshimizu-cq commented on BookManager_iOS/test.swift
> +//
すみません、見落としです。削除しました。

2020-07-13 03:55 UTC, yshimizu-cq commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +        Nuke.loadImage(with: url, into: imageView)
UIImageExtensionを作成して、EditBookViewControllerとBookListCellのNukeを1箇所にまとめました！
合わせてimportも削除しました。

2020-07-13 05:35 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    enum EditBookError: Error {
Validation処理を1箇所にまとめて、呼び出す形に変更しました！

2020-07-13 05:42 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Account/AccountViewModel.swift
> +    func account(successAction: @escaping () -> Void, errorAction: @escaping (Error) -> Void) {
account=logoutです。分かりにくいので命名変更しました！

2020-07-13 05:47 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +                UserDefaultsUtil.set(value: inputValue.id ?? 0, forKey: "book")
当初の実装が残ったままになっていました。
不要なので削除しました。

2020-07-13 06:35 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    var keychain: Keychain {
KeychainをKeychainManagerに集約し、importも削除しました。

2020-07-13 06:53 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/UserDefaultsUtil.swift
> +        UserDefaults.standard.set(value, forKey: forKey)
ありません。firstLaunchのみなので提案頂いた書き方に変更しました。

2020-07-13 08:34 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +        var request = URLRequest(url: url!)
オプショナルバインディングでアンラップ回避しました！

2020-07-14 10:48 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +    case login(UserRequest)
なるほど、勉強になります！
各アクション毎にProtocolで定義する形に変更しました。
URLSessionとAPIClientを大幅に変更したので、再度レビュー頂くことになり申し訳ないですがよろしくお願いします！

2020-07-14 10:54 UTC, yshimizu-cq commented
@caraquri-yomura (cc: @caraquri-ikawashima ）

遅くなりましたが、ご指摘頂いた点を修正しましたので再度レビューお願いします！
川島さんからご指摘頂いた点も合わせて修正しています。

2020-07-14 11:25 UTC, caraquri-ikawashima reviewed
コメントしました！ ご確認お願いします 👍

2020-07-14 11:25 UTC, caraquri-ikawashima commented on BookManager_iOS/Info.plist
> +	<key>NSAppleMusicUsageDescription</key>
```
NSAppleMusicUsageDescription
```
おそらくこれいらないですね。上のPhotoLibraryのパーミッションだけでよいかと思います

2020-07-14 11:25 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/KeychainAccess.swift
> +class KeychainManager {
structの方使っていてこちら不要だと思うので削除でお願いします 🙏

2020-07-14 11:25 UTC, caraquri-ikawashima commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +        sendBookListRequest(initial: true)
initialとは何を指していますかね？ 🤔 
初回読み込みですかね

2020-07-14 11:25 UTC, caraquri-ikawashima commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +    var addBookButton: UIBarButtonItem!
こもprivate でよさそうです！

2020-07-14 11:25 UTC, caraquri-ikawashima commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +        super.viewWillAppear(animated)
どこのタイミングでロードしたいのかで変わってくるかとおもいますが、
viewWillAppearで currrentpageを+=1していくような形でよいかと思うのですが、この辺なにか意図ありますか？ 🤔

2020-07-14 11:25 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    var selectedBook: Book?
これviewControllerから直接参照しちゃってるので
イニシャライザで渡す形でもよいかと思います。
どちらでも大丈夫です

2020-07-14 11:25 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    func editBook(inputValue: inputValue, successAction: @escaping () -> Void, errorAction: @escaping (String) -> Void) {
他のところもそうなのですが、
１行が長いので適宜改行お願いします 🙏

2020-07-15 01:02 UTC, yshimizu-cq commented on BookManager_iOS/Info.plist
> +	<key>NSAppleMusicUsageDescription</key>
不要でしたので削除しました！

2020-07-15 01:04 UTC, yshimizu-cq commented on BookManager_iOS/Model/KeychainAccess.swift
> +class KeychainManager {
すみません、消し忘れです。削除しました！

2020-07-15 01:43 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    func editBook(inputValue: inputValue, successAction: @escaping () -> Void, errorAction: @escaping (String) -> Void) {
全体的に改行を見直しました！

2020-07-15 01:44 UTC, yshimizu-cq commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +    var addBookButton: UIBarButtonItem!
private追加しました！

2020-07-15 07:21 UTC, yshimizu-cq commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +        sendBookListRequest(initial: true)
初回読み込み時に、最初の1ページ（20件）を取得するためにinital: trueを指定しています。

2020-07-15 07:21 UTC, yshimizu-cq commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +        super.viewWillAppear(animated)
画面読み込み処理をviewDidLoadに移動して、Viewが呼ばれた最初の一回だけ読み込むようにしました。

2020-07-15 08:03 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    var selectedBook: Book?
イニシャライザを使った書き方に変更しました。

2020-07-15 08:04 UTC, yshimizu-cq commented
@caraquri-yomura 、@caraquri-ikawashima 

ご指摘頂いた点を修正しましたのでお手隙の際のレビューよろしくお願いします！

2020-07-15 10:17 UTC, caraquri-ikawashima reviewed
@yshimizu-cq 
追加でコメントしましたのでご確認お願いします 😃

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/View/Account/AccountViewController.swift
> +                let logoutDialog = UIAlertController(
AlertってshowAlertのようなメソッド作ってましたよね？？
ボタン１つのアラートとボタン２つのアラートのメソッドをそれぞれ用意してあげて使い分けるような形にすればよいかと思います！

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +        guard let cell: BookListCell = (tableView.dequeueReusableCell(
細かいですが　(tableView.~~~~ as? BookListCell)  のカッコいらないと思います！

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +
ここですが、複数箇所使っているのでUIImageのextensionで
以下のようにするのはいかがでしょう 🤔 

```
extension UIImage {

    var asBase64EncodedString: String? {
        self.pngData()?.base64EncodedString()
    }
}

image.asBase64EncodedString
```

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/Extension/UIImageExtension.swift
> +    static func showImage(url: URL, imageView: UIImageView) {
UIImageViewの拡張なので UIImageViewをわざわざ引数で渡す必要はないですね
UIImageViewをselfで取得できるような形にするのがよいかと思います

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/ja.lproj/Localizable.strings
> +"dateFormat" = "yyyy/MM/dd";
これって使ってます？？？

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +    private func sendBookListRequest(initial: Bool) {
viewDidLoadで初回呼び出しが明示的になっているのでinitial不要かと思います!!

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +        let id: Int?
ここって必須な気がするのですが、入ってこない場合てありますかね？　🤔

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +            return "/books/" + id!.description
ここ文字列の中で変数展開していれてあげればよいと思います

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Response/BookResponse.swift
> +    var purchaseDate: String?
imageに関しては制限があるのでわかるのですが
他のものってオプショナルですかね？？ 🤔 
API仕様書通りであればいいのですが、ほとんど値が入ってくる認識なのでオプショナルにしなくてよい認識です

2020-07-15 10:17 UTC, caraquri-ikawashima commented on BookManager_iOS/Protocol/ValidatorProtocol.swift
> +            return "\(formName)を入力してください"
この辺Stringファイルにまとめて R.string.form(formName)のようにできるはずなのでそちらのほうがよいかと思います 🙆‍♀️ 
https://qiita.com/simorgh3196/items/c9b04377dfa1425085c3

2020-07-15 10:43 UTC, yshimizu-cq commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +        guard let cell: BookListCell = (tableView.dequeueReusableCell(
ほんとですね、気付きませんでした…
指摘ありがとうございます！

2020-07-15 10:43 UTC, yshimizu-cq commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +
確かにその方が良いですね！
提案ありがとうございます。参考にさせて頂きました！

2020-07-15 10:53 UTC, yshimizu-cq commented on BookManager_iOS/ja.lproj/Localizable.strings
> +"dateFormat" = "yyyy/MM/dd";
すみません、使ってないです。
Localizable.stringsの中身を整理できていなかったので、他のstringsも合わせて整理しました！

2020-07-15 11:15 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +            return "/books/" + id!.description
変数展開する形に変更しました！

2020-07-15 11:15 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +        let id: Int?
すみません、idは必須ですね！変更しました！

2020-07-15 11:15 UTC, yshimizu-cq commented on BookManager_iOS/Model/Response/BookResponse.swift
> +    var purchaseDate: String?
APIの仕様書に合わせて、idとnameは必須、その他は任意という形にしましたがよろしいでしょうか？

2020-07-15 11:20 UTC, caraquri-ikawashima commented on BookManager_iOS/Model/Response/BookResponse.swift
> +    var purchaseDate: String?
はい、仕様書にあわせてもらえれば大丈夫です 🙆‍♂️

2020-07-15 11:55 UTC, yshimizu-cq commented on BookManager_iOS/Model/Response/BookResponse.swift
> +    var purchaseDate: String?
了解です！ありがとうございます！

2020-07-16 03:28 UTC, yshimizu-cq commented on BookManager_iOS/Protocol/ValidatorProtocol.swift
> +            return "\(formName)を入力してください"
この辺り一式、R.string...の書き方に変更しました！

2020-07-16 04:11 UTC, yshimizu-cq commented on BookManager_iOS/Extension/UIImageExtension.swift
> +    static func showImage(url: URL, imageView: UIImageView) {
selfで呼び出せる形に書き換えました！

2020-07-16 05:23 UTC, yshimizu-cq commented on BookManager_iOS/View/Account/AccountViewController.swift
> +                let logoutDialog = UIAlertController(
Alert処理をextensionに移動して呼び出す形にしました！

2020-07-16 05:52 UTC, yshimizu-cq commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +    private func sendBookListRequest(initial: Bool) {
すみません、確認させてください。
初回呼び出しと下スクロール時でinitalをtrue,falseで場合分けしてcurrentPageに入れる値を変えているのですが、そのような書き方にしない方が良いということでしょうか？

2020-07-16 05:54 UTC, yshimizu-cq commented
@caraquri-ikawashima cc: @caraquri-yomura 

ご指摘頂いた点を修正しましたのでお手数ですが、ご確認お願いします！

2020-07-16 09:46 UTC, caraquri-ikawashima approved these changes
@yshimizu-cq 

いくつかコメントしましたが、微修正だと思うのでapproveします！！
お疲れさまでした 😃 

@caraquri-yomura 
確認お願いします

2020-07-16 09:46 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +        title: String,
ここもid入ってくる認識なのでオプショナル外しておいてください 🙆‍♂️

2020-07-16 09:46 UTC, caraquri-ikawashima commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +            id: selectedBook!.id,
👆そうすればこの辺の強制アンラップいらなくなる認識です

2020-07-16 09:46 UTC, caraquri-ikawashima commented on BookManager_iOS/Extension/UIAlertExtension.swift
> +            handler: { _ in
固有のロジックをもちたくないので
引数にクロージャーを指定して、遷移の処理自体を引数で渡す形にすればよいと思います

```
func showSelectiveAlert(handler: ((UIAlertAction) -> Void)? = nil) {
        alert.addAction(UIAlertAction(
            title: R.string.localizable.okay(),
            style: .default,
            handler: handler)
}

let handler: ((UIAlertAction) -> Void)? = {
    let storyboard = R.storyboard.login().instantiateInitialViewController()

                guard let window =
                    UIApplication.shared.windows.filter({$0.isKeyWindow}).first else { return }

                window.rootViewController = storyboard
}

showSelectiveAlert(handler: handler)
```

2020-07-16 10:40 UTC, yshimizu-cq commented on BookManager_iOS/Extension/UIAlertExtension.swift
> +            handler: { _ in
確かにそうですね、考えられていませんでした。
提案頂いた通り、固有ロジックをViewModelに書く方法に変更しました！

2020-07-16 10:40 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +            id: selectedBook!.id,
selectedBookのオプショナルを外して強制アンラップを削除しました！

2020-07-16 10:40 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +        title: String,
すみません、見落としです。修正しました！

2020-07-16 21:51 UTC, caraquri-ikawashima commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +    private func sendBookListRequest(initial: Bool) {
これ見逃してました 💦 
簡易にcurrentPageの初期値を0にしておいてsendBookListRequestがよばれたら+1 加算してくでいいと思ったのですが、
まあ今のままでも大丈夫です。

ただ、これだと画面表示時のsendBookListRequestでAPI通信が失敗。
その後スクロールしてsendBookListRequestが呼ばれたら2ページ目から表示されてしまうと思います。

なので厳密にやるのであればtotalPageとcurrentPageという2つのプロパティをもっておいて
sendBookListRequestの結果としてtotalpagesのレスポンスが返ってきたらそれをもとにプロパティを更新する→totalpagesとcurrentPageの値を見てcurrentPageに+1するかどうか制御するがよいと思います。

2020-07-17 01:34 UTC, yshimizu-cq commented on BookManager_iOS/View/BookList/BookListViewController.swift
> +    private func sendBookListRequest(initial: Bool) {
なるほど、確かに初回取得を失敗するパターンを考えられていませんでした。
研修の日程考慮しながら、チャレンジしてみます！

2020-07-17 04:01 UTC, ghost approved these changes
@yshimizu-cq 問題なさそうです！
LGTM

2020-07-17 10:50 UTC, miyoshitakaaki requested changes
🙏

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +        if let error: [ValidationError] = extractLoginValidationErrors(
早期リターンはguard使いましょう

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/ViewModel/Signup/SignupViewModel.swift
> +        if let error: [ValidationError] = extractSignupValidationErrors(
guardが望ましい

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    func extractLoginValidationErrors(
privateにできる？

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +        errors.forEach { messages.append($0.description!) }
アンラップ 🆖

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    func generateErrorMessage(by errors: [ValidationError]) -> String {
これもprivateにできる？

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/ViewModel/Signup/SignupViewModel.swift
> +    func extractSignupValidationErrors(
private

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/Signup/SignupViewModel.swift
> +    func generateErrorMessage(by errors: [ValidationError]) -> String {
private

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    func extracteditBookValidationErrors(title: String) -> [ValidationError]? {
private

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    func generateErrorMessage(by errors: [ValidationError]) -> String {
private

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +        errors.forEach { messages.append($0.description!) }
アンラップ 🆖

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +        if let error: [ValidationError] = extracteditBookValidationErrors(
やりたいことって、Errorをextractしたり、エラーメッセージをgenerateしたいわけではなくて、
入力内容をvalidateしたいんだよね？
素直にvalidateメソッドを作ったほうが良いよ
extracteditBookValidationErrorsだけ、generateErrorMessageだけ使う想定無いよね？

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/BookList/BookListViewModel.swift
> +    func update(books: [Book]) {
updateっていうかsetかな
更新というより、代入しているので

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/BookList/BookListViewModel.swift
> +    func setBookList(
命名はsetよりもfetchが実装内容にあっていると思う

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    func extractAddBookValidationErrors(title: String) -> [ValidationError]? {
private

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    func generateErrorMessage(by errors: [ValidationError]) -> String {
private

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    }
すごく複雑に見える。。。
せめて`validationResults.filter({ !$0.isValid })` は共通化しよう

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    typealias inputValue = (
型名は大文字で始めてください、InputValue

あとtupleは経験則から話すと、できることが少なすぎて、あまり使わないほうがよいです
今は構わないけど、何らかのprotocolに準拠させたいときにできません
とにかくstructを使うことです、変更に耐えやすい作りになります

2020-07-17 10:50 UTC, miyoshitakaaki commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +            inputValue: (id!, title, imageStr, Int(price)!, date),
アンラップ禁止
!で全体を検索かけてほしい

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/Model/Request/UserDefaultsUtil.swift
> +    func setLaunchFlag(value: Any) {
なんでこれだけ `static func` じゃないのかな？

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +                                value: child.value as? String ?? "")
child.valueがIntやBool型のとき、キャスト失敗して空文字が送られるよ
Mirror使うのはいいのだけど、child.valueがAny型なので、
型安全な作りにできないことだけ頭にいれておいてください

2020-07-17 10:50 UTC, miyoshi-cq commented on BookManager_iOS/Protocol/ValidatorProtocol.swift
> +        EmptyValidator(formName: "メールアドレス"),
localizableString使ってるよね？
文言はそちらで管理してほしい 🙏

2020-07-20 02:30 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    func extractLoginValidationErrors(
private追加しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +    func generateErrorMessage(by errors: [ValidationError]) -> String {
private追加しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Signup/SignupViewModel.swift
> +    func extractSignupValidationErrors(
private追加しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Signup/SignupViewModel.swift
> +    func generateErrorMessage(by errors: [ValidationError]) -> String {
private追加しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    func extracteditBookValidationErrors(title: String) -> [ValidationError]? {
private追加しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    func generateErrorMessage(by errors: [ValidationError]) -> String {
private追加しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/BookList/BookListViewModel.swift
> +    func update(books: [Book]) {
確かにそうですね。しっかり命名意識できていませんでした。
`set`に変更しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/BookList/BookListViewModel.swift
> +    func setBookList(
こちらもしっかり命名意識できていませんでした。
`fetch`に変更しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    func extractAddBookValidationErrors(title: String) -> [ValidationError]? {
private追加しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    func generateErrorMessage(by errors: [ValidationError]) -> String {
private追加しました！

2020-07-20 02:31 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/UserDefaultsUtil.swift
> +    func setLaunchFlag(value: Any) {
すみません、見落としです。
`static func`に変更しました！

2020-07-20 02:38 UTC, yshimizu-cq commented on BookManager_iOS/Protocol/ValidatorProtocol.swift
> +        EmptyValidator(formName: "メールアドレス"),
文言をLocalizableStringで管理するよう変更しました！

2020-07-20 03:10 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    }
複雑ですみません、良い書き方が分からず…
`validationResults.filter({ !$0.isValid })`を共通化しました！

2020-07-20 06:45 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +        if let error: [ValidationError] = extracteditBookValidationErrors(
はい、別々で使う想定はしていないです。
validateメソッドを作ってエラーハンドリングするようにしました！

2020-07-20 07:10 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +        errors.forEach { messages.append($0.description!) }
アンラップ回避しました！
また、UIレビューで対応した画面遷移のstoryboard取得以外で、アンラップ`!`がないか全体を確認しました。

2020-07-20 07:10 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +        errors.forEach { messages.append($0.description!) }
アンラップ回避しました！
また、UIレビューで対応した画面遷移のstoryboard取得以外で、アンラップ`!`がないか全体を確認しました。

2020-07-20 07:10 UTC, yshimizu-cq commented on BookManager_iOS/View/EditBook/EditBookViewController.swift
> +            inputValue: (id!, title, imageStr, Int(price)!, date),
アンラップ回避しました！
また、UIレビューで対応した画面遷移のstoryboard取得以外で、アンラップ`!`がないか全体を確認しました。

2020-07-20 07:37 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +        if let error: [ValidationError] = extractLoginValidationErrors(
早期リターンのとき、guardを使って異常系であることを読み手に分かりやすくする、とのこと勉強になります。
今回validation処理の変更に伴って、if文で`validateLogin`メソッドを呼び出して、`true`のとき`return`するような書き方に変更したのですが、この場合だと`if ~ { return }`の書き方の方が分かりやすいと思ったのですが、いかがでしょうか？

2020-07-20 07:37 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Signup/SignupViewModel.swift
> +        if let error: [ValidationError] = extractSignupValidationErrors(
上記同様です。

2020-07-20 08:01 UTC, yshimizu-cq commented on BookManager_iOS/Model/Request/URLSessionRequest.swift
> +                                value: child.value as? String ?? "")
なるほど、確かにそうですね。そこまで配慮できていませんでした。勉強になります。
`Mirror`を使った書き方しか調べられなかったので、ベターな書き方できないかもう少し探ってみます。

2020-07-20 08:13 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    typealias inputValue = (
大文字始まりに変更しました！
そうなんですね、structとのメリデメ理解できていなかったので確認しておきます！

2020-07-20 09:28 UTC, miyoshitakaaki requested changes
typealiasが小文字で始まってるのたくさんあるよー

2020-07-20 09:28 UTC, miyoshi-cq commented on BookManager_iOS/Model/KeychainManager.swift
> +    static var keychain: Keychain {
毎回インスタンス作ってもしょうがないので、シングルトンにしてもらえると 🙏

2020-07-20 09:28 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    typealias request = Request.AddBook
typealiasは大文字で始めましょう
Request

2020-07-20 09:28 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +            id: -1,
-1ってなんだろう 🤔

2020-07-20 09:28 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    typealias inputValue = (
大文字で 🙏

2020-07-20 09:28 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +                               failerHandler: (String) -> Void) -> Bool {
タイポ 🙅‍♂️ 
```suggestion
                               failureHandler: (String) -> Void) -> Bool {
```

2020-07-20 09:33 UTC, miyoshitakaaki requested changes

2020-07-20 09:33 UTC, miyoshi-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +        if let error: [ValidationError] = extractLoginValidationErrors(
あー、extractLoginValidationErrorsがErrorを返すのか
そうね、ifでいいと思う 🙏

2020-07-20 10:15 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +    typealias request = Request.AddBook
すみません、大文字に変更しました！
その他のtypealiasもチェックしました

2020-07-20 10:15 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/Login/LoginViewModel.swift
> +                               failerHandler: (String) -> Void) -> Bool {
お恥ずかしい…修正しました！

2020-07-20 10:15 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/EditBook/EditBookViewModel.swift
> +    typealias inputValue = (
すみません、大文字に変更しました！
その他のtypealiasもチェックしました

2020-07-20 10:26 UTC, yshimizu-cq commented on BookManager_iOS/ViewModel/AddBook/AddBookViewModel.swift
> +            id: -1,
もともと初期化で`id`に-1を入れていたのですが、AddBookのRequestに`id`は不要なので、そのように変更しました！

2020-07-20 11:07 UTC, yshimizu-cq commented on BookManager_iOS/Model/KeychainManager.swift
> +    static var keychain: Keychain {
シングルトンを使った書き方に変更しました！

2020-07-20 11:09 UTC, yshimizu-cq commented
`typealias`のチェック不足すみませんでした。
ご指摘頂いた点を修正しましたので、お手数おかけしますが、レビューお願いします！

2020-07-21 01:15 UTC, ghost approved these changes
よさそうです、LGTM

2020-07-21 01:18 UTC, merged